In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("housing.csv")

In [4]:
df['income_cat']=pd.cut(df['median_income'],bins=[0,1.5,3.0,4.5,6.0,np.inf],labels=[1,2,3,4,5])

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype   
---  ------              --------------  -----   
 0   longitude           20640 non-null  float64 
 1   latitude            20640 non-null  float64 
 2   housing_median_age  20640 non-null  float64 
 3   total_rooms         20640 non-null  float64 
 4   total_bedrooms      20433 non-null  float64 
 5   population          20640 non-null  float64 
 6   households          20640 non-null  float64 
 7   median_income       20640 non-null  float64 
 8   median_house_value  20640 non-null  float64 
 9   ocean_proximity     20640 non-null  object  
 10  income_cat          20640 non-null  category
dtypes: category(1), float64(9), object(1)
memory usage: 1.6+ MB


In [6]:
from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)

for train_index, test_index in split.split(df, df["income_cat"]):
    strat_train_set = df.loc[train_index]
    strat_test_set = df.loc[test_index]

In [7]:
df=strat_train_set

In [8]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
12655    -121.46     38.52                29.0       3873.0           797.0   
15502    -117.23     33.09                 7.0       5320.0           855.0   
2908     -119.04     35.37                44.0       1618.0           310.0   
14053    -117.13     32.75                24.0       1877.0           519.0   
20496    -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
15174    -117.07     33.03                14.0       6665.0          1231.0   
12661    -121.42     38.51                15.0       7901.0          1422.0   
19263    -122.72     38.44                48.0        707.0           166.0   
19140    -122.70     38.31                14.0       3155.0           580.0   
19773    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income  median_house_value  \
12655      2237.0       706.0         2.1736             72100.0   
15502      2015.0       768.0         6.3373            279600.0   
2908        667.0       300.0         2.8750             82700.0   
14053       898.0       483.0         2.2264            112500.0   
20496      1837.0       580.0         4.4964            238300.0   
...           ...         ...            ...                 ...   
15174      2026.0      1001.0         5.0900            268500.0   
12661      4769.0      1418.0         2.8139             90400.0   
19263       458.0       172.0         3.1797            140400.0   
19140      1208.0       501.0         4.1964            258100.0   
19773       625.0       197.0         3.1319             62700.0   

      ocean_proximity income_cat  
12655          INLAND          2  
15502      NEAR OCEAN          5  
2908           INLAND          2  
14053      NEAR OCEAN          2  
20496       <1H OCEAN          3  
...               ...        ...  
15174       <1H OCEAN          4  
12661          INLAND          2  
19263       <1H OCEAN          3  
19140       <1H OCEAN          3  
19773          INLAND          3  

[16512 rows x 11 columns]

In [9]:
housing = strat_train_set.drop("median_house_value", axis=1)
housing_labels = strat_train_set["median_house_value"].copy()

In [10]:
housing

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
12655    -121.46     38.52                29.0       3873.0           797.0   
15502    -117.23     33.09                 7.0       5320.0           855.0   
2908     -119.04     35.37                44.0       1618.0           310.0   
14053    -117.13     32.75                24.0       1877.0           519.0   
20496    -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
15174    -117.07     33.03                14.0       6665.0          1231.0   
12661    -121.42     38.51                15.0       7901.0          1422.0   
19263    -122.72     38.44                48.0        707.0           166.0   
19140    -122.70     38.31                14.0       3155.0           580.0   
19773    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income ocean_proximity income_cat  
12655      2237.0       706.0         2.1736          INLAND          2  
15502      2015.0       768.0         6.3373      NEAR OCEAN          5  
2908        667.0       300.0         2.8750          INLAND          2  
14053       898.0       483.0         2.2264      NEAR OCEAN          2  
20496      1837.0       580.0         4.4964       <1H OCEAN          3  
...           ...         ...            ...             ...        ...  
15174      2026.0      1001.0         5.0900       <1H OCEAN          4  
12661      4769.0      1418.0         2.8139          INLAND          2  
19263       458.0       172.0         3.1797       <1H OCEAN          3  
19140      1208.0       501.0         4.1964       <1H OCEAN          3  
19773       625.0       197.0         3.1319          INLAND          3  

[16512 rows x 10 columns]

In [11]:
housing_labels

12655     72100.0
15502    279600.0
2908      82700.0
14053    112500.0
20496    238300.0
           ...   
15174    268500.0
12661     90400.0
19263    140400.0
19140    258100.0
19773     62700.0
Name: median_house_value, Length: 16512, dtype: float64

In [12]:
from sklearn.impute import SimpleImputer

In [13]:
imputer = SimpleImputer(strategy="median")

In [14]:
housing_num = housing.select_dtypes(include=[np.number])

In [15]:
imputer.fit_transform(housing_num)

array([[-1.2146e+02,  3.8520e+01,  2.9000e+01, ...,  2.2370e+03,
         7.0600e+02,  2.1736e+00],
       [-1.1723e+02,  3.3090e+01,  7.0000e+00, ...,  2.0150e+03,
         7.6800e+02,  6.3373e+00],
       [-1.1904e+02,  3.5370e+01,  4.4000e+01, ...,  6.6700e+02,
         3.0000e+02,  2.8750e+00],
       ...,
       [-1.2272e+02,  3.8440e+01,  4.8000e+01, ...,  4.5800e+02,
         1.7200e+02,  3.1797e+00],
       [-1.2270e+02,  3.8310e+01,  1.4000e+01, ...,  1.2080e+03,
         5.0100e+02,  4.1964e+00],
       [-1.2214e+02,  3.9970e+01,  2.7000e+01, ...,  6.2500e+02,
         1.9700e+02,  3.1319e+00]])

In [16]:
housing

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
12655    -121.46     38.52                29.0       3873.0           797.0   
15502    -117.23     33.09                 7.0       5320.0           855.0   
2908     -119.04     35.37                44.0       1618.0           310.0   
14053    -117.13     32.75                24.0       1877.0           519.0   
20496    -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
15174    -117.07     33.03                14.0       6665.0          1231.0   
12661    -121.42     38.51                15.0       7901.0          1422.0   
19263    -122.72     38.44                48.0        707.0           166.0   
19140    -122.70     38.31                14.0       3155.0           580.0   
19773    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income ocean_proximity income_cat  
12655      2237.0       706.0         2.1736          INLAND          2  
15502      2015.0       768.0         6.3373      NEAR OCEAN          5  
2908        667.0       300.0         2.8750          INLAND          2  
14053       898.0       483.0         2.2264      NEAR OCEAN          2  
20496      1837.0       580.0         4.4964       <1H OCEAN          3  
...           ...         ...            ...             ...        ...  
15174      2026.0      1001.0         5.0900       <1H OCEAN          4  
12661      4769.0      1418.0         2.8139          INLAND          2  
19263       458.0       172.0         3.1797       <1H OCEAN          3  
19140      1208.0       501.0         4.1964       <1H OCEAN          3  
19773       625.0       197.0         3.1319          INLAND          3  

[16512 rows x 10 columns]

In [17]:
set(housing['ocean_proximity'])

{'<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'}

In [18]:
housing_cat = housing[["ocean_proximity"]]
housing_cat.head()

ocean_proximity
12655          INLAND
15502      NEAR OCEAN
2908           INLAND
14053      NEAR OCEAN
20496       <1H OCEAN

In [19]:
from sklearn.preprocessing import OrdinalEncoder

ordinal_encoder = OrdinalEncoder()
housing_cat_encoded = ordinal_encoder.fit_transform(housing_cat)

In [20]:
housing_cat=pd.DataFrame(housing_cat,columns=housing.columns,index=housing.index)

In [21]:
from sklearn.preprocessing import OneHotEncoder

cat_encoder = OneHotEncoder()
housing_cat_1hot = cat_encoder.fit_transform(housing_cat)

In [22]:
housing_cat_1hot.toarray()

array([[1., 1., 1., ..., 0., 0., 1.],
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 0., 0., 1.],
       ...,
       [1., 1., 1., ..., 0., 0., 1.],
       [1., 1., 1., ..., 0., 0., 1.],
       [1., 1., 1., ..., 0., 0., 1.]])

In [23]:
cat_encoder = OneHotEncoder(sparse=False)
housing_cat_1hot = cat_encoder.fit_transform(housing_cat)

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'

In [24]:

cat_encoder.categories_

[array([nan]),
 array([nan]),
 array([nan]),
 array([nan]),
 array([nan]),
 array([nan]),
 array([nan]),
 array([nan]),
 array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object),
 array([nan])]

In [25]:
housing

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
12655    -121.46     38.52                29.0       3873.0           797.0   
15502    -117.23     33.09                 7.0       5320.0           855.0   
2908     -119.04     35.37                44.0       1618.0           310.0   
14053    -117.13     32.75                24.0       1877.0           519.0   
20496    -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
15174    -117.07     33.03                14.0       6665.0          1231.0   
12661    -121.42     38.51                15.0       7901.0          1422.0   
19263    -122.72     38.44                48.0        707.0           166.0   
19140    -122.70     38.31                14.0       3155.0           580.0   
19773    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income ocean_proximity income_cat  
12655      2237.0       706.0         2.1736          INLAND          2  
15502      2015.0       768.0         6.3373      NEAR OCEAN          5  
2908        667.0       300.0         2.8750          INLAND          2  
14053       898.0       483.0         2.2264      NEAR OCEAN          2  
20496      1837.0       580.0         4.4964       <1H OCEAN          3  
...           ...         ...            ...             ...        ...  
15174      2026.0      1001.0         5.0900       <1H OCEAN          4  
12661      4769.0      1418.0         2.8139          INLAND          2  
19263       458.0       172.0         3.1797       <1H OCEAN          3  
19140      1208.0       501.0         4.1964       <1H OCEAN          3  
19773       625.0       197.0         3.1319          INLAND          3  

[16512 rows x 10 columns]

In [26]:
original=df

In [27]:
original

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
12655    -121.46     38.52                29.0       3873.0           797.0   
15502    -117.23     33.09                 7.0       5320.0           855.0   
2908     -119.04     35.37                44.0       1618.0           310.0   
14053    -117.13     32.75                24.0       1877.0           519.0   
20496    -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
15174    -117.07     33.03                14.0       6665.0          1231.0   
12661    -121.42     38.51                15.0       7901.0          1422.0   
19263    -122.72     38.44                48.0        707.0           166.0   
19140    -122.70     38.31                14.0       3155.0           580.0   
19773    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income  median_house_value  \
12655      2237.0       706.0         2.1736             72100.0   
15502      2015.0       768.0         6.3373            279600.0   
2908        667.0       300.0         2.8750             82700.0   
14053       898.0       483.0         2.2264            112500.0   
20496      1837.0       580.0         4.4964            238300.0   
...           ...         ...            ...                 ...   
15174      2026.0      1001.0         5.0900            268500.0   
12661      4769.0      1418.0         2.8139             90400.0   
19263       458.0       172.0         3.1797            140400.0   
19140      1208.0       501.0         4.1964            258100.0   
19773       625.0       197.0         3.1319             62700.0   

      ocean_proximity income_cat  
12655          INLAND          2  
15502      NEAR OCEAN          5  
2908           INLAND          2  
14053      NEAR OCEAN          2  
20496       <1H OCEAN          3  
...               ...        ...  
15174       <1H OCEAN          4  
12661          INLAND          2  
19263       <1H OCEAN          3  
19140       <1H OCEAN          3  
19773          INLAND          3  

[16512 rows x 11 columns]

In [28]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# Reset index so alignment works
df_reset = df.reset_index(drop=True)

encoder = OneHotEncoder(sparse_output=False)
ocean_encoded = encoder.fit_transform(df_reset[["ocean_proximity"]])

# Create dataframe with matching index
ocean_encoded_df = pd.DataFrame(
    ocean_encoded,
    columns=encoder.get_feature_names_out(["ocean_proximity"])
)

# Concatenate safely
df_final = pd.concat([df_reset.drop("ocean_proximity", axis=1), ocean_encoded_df], axis=1)

print(df_final.head())


   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.46     38.52                29.0       3873.0           797.0   
1    -117.23     33.09                 7.0       5320.0           855.0   
2    -119.04     35.37                44.0       1618.0           310.0   
3    -117.13     32.75                24.0       1877.0           519.0   
4    -118.70     34.28                27.0       3536.0           646.0   

   population  households  median_income  median_house_value income_cat  \
0      2237.0       706.0         2.1736             72100.0          2   
1      2015.0       768.0         6.3373            279600.0          5   
2       667.0       300.0         2.8750             82700.0          2   
3       898.0       483.0         2.2264            112500.0          2   
4      1837.0       580.0         4.4964            238300.0          3   

   ocean_proximity_<1H OCEAN  ocean_proximity_INLAND  ocean_proximity_ISLAND  \
0                 

In [29]:
df_final=df_final.drop("income_cat",axis=1)

In [ ]:
df_final